### ISSUE TITLE
Concatenation of javascripts doesn't work

### ISSUE THREAD

**Issue by jeremycod** [souly1/ng-walkthrough#16]
I'm trying to integrate ng-walkthrough with [Moodle mobile 2](https://github.com/moodlehq/moodlemobile2). However, I can't change core Moodle code, but only my module located at www/addons/mymodulename.
Moodle concatenates all the javascript files to www/build/mm.bundle.js and and all css files to www/build/mm.bundle.css, and includes it to index.html. Adding walkthrough in this way results in the following error:
![selection_058](https://cloud.githubusercontent.com/assets/5204745/10466909/c587de52-71ab-11e5-840a-38d36f67efc3.png)

The error disappears if I include ng-walkthrough.js and ng-walkthrough.css directly in index.html file, but I can't do that.

I'm using most recent code.

Zoran

**Comment by matthieu-D** [comment]
Anyone solved this or know another plugin easy to use?

**Comment by souly1** [comment]
Hi @matthieu-D and @jeremycod  , new version has been released, can you please update me if the issue was solved?

Thanks

**Comment by matthieu-D** [comment]
I gave it a shot.
Since the bower registry hasn't been updated yet I just copied paste the main js and css file.
Not working, important point, I'm working with xcode to log my real device, I don't have an error, my problem is that every time that I add the directive to a view I get this : 
![image1](https://cloud.githubusercontent.com/assets/5333018/12537733/6a774338-c294-11e5-91d7-6b11b0e82987.PNG)

**Comment by souly1** [comment]
Interesting error, looks quite different from Jeremycod's. If you've replaced the js and css the changes should have persisted. 
Anyhow,The bower registry has been updated, so you can reinstall.
Take note, if you're using any gesture icons (swipe/tap), make sure to load the 
'ng-walkthrough.tap_icons.js' script as this is now used to load gestures, the icons folder has been removed for production.

**Comment by matthieu-D** [comment]
I don't have the weird html rendered anymore, good.
But the walkthrough is not showing properly, I'll see that later, doesn't
seem to be very hard to fix(css).

2016-01-25 6:49 GMT-05:00 Ophir Stern <notifications@github.com>:

> Interesting error, looks quite different from Jeremycod's. If you've
> replaced the js and css the changes should have persisted.
> Anyhow,The bower registry has been updated, so you can reinstall.
> Take note, if you're using any gesture icons (swipe/tap), make sure to
> load the
> 'ng-walkthrough.tap_icons.js' script as this is now used to load gestures,
> the icons folder has been removed for production.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/souly1/ng-walkthrough/issues/16#issuecomment-174482897>
> .
>



-- 
*Best Regards,*


*Matthieu DRULACEO and Entrepreneur *
*07432328222*

**Comment by matthieu-D** [comment]
I had to manually add the css, my wiredep task didn't recognised didn't add the file.
Everything seems good aside from the iOS 9 bug from https://github.com/souly1/ng-walkthrough/issues/21.

**Comment by souly1** [comment]
Cool, closing this issue, update if reappears
