### ISSUE TITLE
Tip position is always top

### ISSUE THREAD

**Issue by jeremycod** [souly1/ng-walkthrough#17]
tip-location="BOTTOM", but tip is always above focus area and arrow is not displayed properly . If first element of the list has focus, tip is hidden bellow.
![selection_065](https://cloud.githubusercontent.com/assets/5204745/10475145/f8f237f8-71f4-11e5-8954-3b9ee00a058d.png)

Sample code is given [here](https://github.com/jeremycod/ionicsamples)

**Comment by jeremycod** [comment]
In addition to this, tip to specific ion-tab shows area outside the screen.
![selection_066](https://cloud.githubusercontent.com/assets/5204745/10475555/be3783de-71f9-11e5-96ac-67065f204bb0.png)

**Comment by souly1** [comment]
Hi @jeremycod , 
Regarding the first issue, the tip-location attribute is for tip type walkthrough. When using the transparency type with arrow you can offset the arrow edge with the icon-padding-top/icon-padding-left attributes so it won't be hidden on top of the light color background and have it place as you want it to be, or you can change its color to a darker color (currently you'll have to do it manually, hopefully I'll add it in future versions, perhaps by changing the tip-color attribute to something more generic).
Regarding the second issue, it is a known issue and has to do with current Ionic implementation. You could see several older issues opened regarding the subject for possible workarounds.

**Comment by jeremycod** [comment]
Hi @souly1 ,
Your proposal with the icon-padding-top/icon-padding-left attributes doesn't solve the first issue. I tried many possible values, but as the result valuses startLeft and startTop that are written to variable arrowSvgDom are always the same (startLeft:205.5 startTop:66 endTop:221 endLeft:161). It's only endTop and endLeft what is affected by these attributes, and this results in walkthrough looking like this:
![selection_067](https://cloud.githubusercontent.com/assets/5204745/10497529/39c96702-727b-11e5-8af8-b9871ccb118b.png)

At the beginning of the setArrowAndText I have the following:
pointSubjectLeft:-1 pointSubjectTop:194 pointSubjectWidth:412 pointSubjectHeight:54
startLeft:205.5 startTop:66 scope.walkthroughTextElement[0].offsetLeft:62 scope.walkthroughTextElement[0].offsetWidth:287

**Comment by souly1** [comment]
Hi @jeremycod , I've issued a new improved fix using an attribute 'force-caption-location', please update  if issue solved.
Thanks

**Comment by jeremycod** [comment]
Hi @souly1,

Thank you for your work on solving these issues. I'll try this today and let you know. However, in the meantime I already found something that solved the issue for me. Attribute 'caption-on-bottom="true"' helped in these specific cases I had the problem. Is that something similar or 'force-caption-location' is better alternative?

For the other issue, I found that getBoundingClientRect is where the problems come from. In some cases it always returns 0,0,0,0, and this problem is already reported elsewhere. At the moment I found some dirty fix. I added attributes 'focusPaddingLeft', and 'focusPaddingLeft' which help me to manually set offset when I have such problem. I know it's not best solution, but it would work until we figure out something else.

Thanks

**Comment by souly1** [comment]
Cool, If you managed then that's what's important. if some day you require new features of the main branch feel free to check out force-caption-location which works better that the caption-on-bottom from another branch as it was not a generic solution and caused regression for several walkthroughs.
Closing the issue,
cheers
