### ISSUE TITLE
more image for single "page"

### ISSUE THREAD

**Issue by ziobudda** [souly1/ng-walkthrough#2]
Hi, is it possibile to have more than 1 image for a single page/state  where I need to swipe to see the 2nd, 3rd, etc etc image ? 

Like: 
`<walkthrough>`
`<img src="img1">`
`<img src="img2">`
`</walkthrough>`

M.

**Comment by souly1** [comment]
Hi,
I'm assuming you mean the 3rd demo option, using the transpose. Yes you can't use any simple HTML you like, such as display multiple images

**Comment by ziobudda** [comment]
Hi, Yes I talk about 3rd demo option, but sorry I have not understand how to use multiple image. I need to use my "swipe" to change image or is there an option inside your plugin ? Sorry for bad english and (maybe) for the stupid question.

**Comment by souly1** [comment]
Hey Zio, Sorry for the late reply, 
I'm not sure, but it seems like you  wanted to do a walkthrough  in the 'Tour' pattern (see 'http://www.uxbooth.com/articles/mobile-design-patterns/' what i mean) if that is the case then this walkthrough as it is written today does not solve that pattern.
As long as you managed....
Good luck
