### ISSUE TITLE
Slight vertical gap 

### ISSUE THREAD

**Issue by matthieu-D** [souly1/ng-walkthrough#20]
Hi,
I have slight gap between my id item and the round-icon. Is that something common and easy to fix? Like a padding-icon-top, or maybe I put something bad on my id css?

**Comment by souly1** [comment]
Hi,
Do you perhaps add a print-screen so we could better understand what you mean?

**Comment by matthieu-D** [comment]
sure :
<img width="156" alt="screen shot 2015-10-24 at 09 55 55" src="https://cloud.githubusercontent.com/assets/5333018/10710351/8b25cf8e-7a35-11e5-845d-dd828029b469.png">

**Comment by souly1** [comment]
Assuming this needs to be on the dollar sign, this is not an issue solved by padding and such, but rather shows an issue with calculating the location correctly, which could happen for several different reasons.
The simplest attempt to solve is to place the walkthrough at a higher level within the DOM and see if that solves the issue.
The other option is creating an example on plunkr or similar and we'll take a look at the code...

**Comment by matthieu-D** [comment]
Just seen that in the logs appears :
Unable to find element requested to be focused: #valid-price-button
As an info type log instead of an error or warning.
Really weird because the id is here, if I change for another id, it has the same behaviour.

**Comment by souly1** [comment]
Are those elements dynamic? or under ng-if? Maybe there is a rate condition to them being added to the DOM

**Comment by matthieu-D** [comment]
One is the other not : 

<div ng-if='vm.all().length != 0'> 
      <i class="circle" id='trash-offer'>
        <i class='ionic-icon ion-trash-b'></i>
      </i>
    </div>
  </ion-content>
</ion-view>

**Comment by matthieu-D** [comment]
I'm using it with ionic, it seems that the gap is the same as the header bar height.
Going to try to style=margin-top:-44px.

**Comment by matthieu-D** [comment]
Ok.
I had some tabs that perfectly fit and didn't have a scroll-bar but the tab that I was working didn't fit perfectly for unknown reason and I had  a scroll-bar with  a 40 px to scroll.
I used a ionic-list to make it fit.

**Comment by souly1** [comment]
Well there is handling with the ionic header with automatic testing so sounds interesting that there is an issue for you, I'll look into it when available

**Comment by matthieu-D** [comment]
Hm I have a small vertical gap on iOS9 of the size of the iphone status bar, annoying because iphones have different size of status bars ...

**Comment by matthieu-D** [comment]
I added a -20px  margin-top(the status bar heigth).
It's working on my 5s and on the big 6s-plus  emulated  so I guess it's a quick fix.

**Comment by souly1** [comment]
Haven't tested on iOS aside to emulator but from what you're saying here, a quick simple fix, although somewhat dirty, could be identifying device type and defining height of status bar accordingly (this what you've done?)

**Comment by matthieu-D** [comment]
No I just used +20px since it worked on 5s and 6s plus. Your solution was
my second choice.

**Comment by souly1** [comment]
ok, cool. Thanks

**Comment by chaosLegacy** [comment]
Hi,
I've start using this awesome directive for my company project and i have some difficulties trying to adapt to my needs so what i'm looking for is a way to let the step increment by user action for example click on add client to continue (see picture 1)
my other problem is i have to adapt that on different devices i've found that the directive does not scroll to the element (see picture 2).
<img width="742" alt="screen shot 2016-12-18 at 9 58 33 am" src="https://cloud.githubusercontent.com/assets/11313734/21292824/2ef44ee6-c509-11e6-87b3-d4868bd25367.png">
<img width="427" alt="screen shot 2016-12-18 at 10 02 06 am" src="https://cloud.githubusercontent.com/assets/11313734/21292826/373bf072-c509-11e6-8248-58bf31f4bf81.png">
Thank you sir :)
