### ISSUE TITLE
Bower version does not match npm version

### ISSUE THREAD

**Issue by wrousseau** [souly1/ng-walkthrough#22]
Hi,

Thanks for the module, it looks really good!

Is there a reason why the bower version does not match the npm version ? And more importantly, is there a way to install the package using npm alone ? As I'm using webpack it needs to be able to require the module and I believe it does not work out of the box (probably as the module is trying to parse script tags to find itself in the DOM, in order to find the directive template and the icons from what I understand).

Thanks in advance

**Comment by souly1** [comment]
Hi wrousseau,
There was not special reason for bower/npm not being in sync on same version, thanks for the input.
Regarding npm, there was no way to install via npm because no-one asked :) , now you can install with 'nam install ng-walkthrough'.
