### ISSUE TITLE
Ionic example

### ISSUE THREAD

**Issue by matiastucci** [souly1/ng-walkthrough#23]
Do you have some demo ionic app with ng-walkthrough integrated? Thanks!

**Comment by souly1** [comment]
Hi @matiastucci , no demo specific to ionic exists, what exactly do you need?
There is @hagai26 example for an issue which was closed which uses ionic which you can take a look at, but take note that it is a specific short solution which was created to surface an issue which existed with the directive once.

https://github.com/hagai26/ng-walkthrough-ionic-example
