### ISSUE TITLE
Template path wrong on my Android Install

### ISSUE THREAD

**Issue by Elpetro** [souly1/ng-walkthrough#25]
Great directive, thanks for sharing.
In my tests on Android, it ends up adding plugin.js code in my HTML instead of the tutorial HTML template !
Debugging it seems that in ng-walkthrough.js the line 

>currentScriptPath.replace(new RegExp("ng-walkthrough.js.*"), 'ng-walkthrough.html');

returns
 >"file:///android_asset/www/cordova_plugins.js"
instead of the template file

I could fix it hardcoding the templates and icons path as follows but I guess it's not a clean fix.

>var templateUrl = "lib/ng-walkthrough/ng-walkthrough.html"; 
>var iconsUrl = "lib/ng-walkthrough/icons/";

**Comment by souly1** [comment]
Hi, thanks for the update. actually, as a directive, I think it might be cleaner if there was no dependency on an HTML file, so next version I'll embed the template into the js.
Thanks

**Comment by souly1** [comment]
Hi @Elpetro , new version has been released, can you please update me if the issue was solved?

Thanks
