### ISSUE TITLE
Formatting the caption

### ISSUE THREAD

**Issue by noamleib** [souly1/ng-walkthrough#27]
Hi Guys,
It seems I'm unable to format the caption text not by html or ASS tags.
Am I missing something?

**Comment by souly1** [comment]
Hi @noamleib , what caption text are you referring to, as there is no caption field defined? do you mean the whole text in the ballon?

**Comment by noamleib** [comment]
Hi @souly1 
Yes, I'm referring to the main-caption directive (main-caption="This is some text"). Since the documentation mentions the text is formidable (

> main-caption (optional) - Any walkthrough type. This is the text that will be displayed in the walk-through. Text can be formatted

).
In my case, it's not a balloon since I'm using the transparency  walkthrough-type.

**Comment by souly1** [comment]
Oops, your totally right, I forgot the attribute is called "main-caption", so you try through CSS to format text and it doesn't work?

**Comment by noamleib** [comment]
Tried to embed in the caption some html tags (h, p etc). Didn't work :-(

**Comment by souly1** [comment]
Could you perhaps add a plunker demo or cut n' paste code of what's not working?
Thanks

**Comment by noamleib** [comment]
Lets say in JS I'm Doing:
$rootScope.captionSchedule = "Lets Start! \n To start a scheduling process click this button to tell Pepper who you would like to meet with."

HTML:
  <walkthrough
        id="walkthrough_schedulebutton"
        walkthrough-type="transparency"
        focus-element-id="schedule_button"
        icon="single_tap"
        force-caption-location="BOTTOM"
        main-caption="{{captionSchedule}}"
        is-active="WTSchedule"
        use-button="false">
  </walkthrough>

The only Tag I was able to incorporate is the \n.
I was wondering if i could do somthing like this:

$rootScope.captionSchedule = "<h1>Lets Start! </h1> <p>To start a scheduling process click this button to tell Pepper who you would like to meet with.<p>"

**Comment by souly1** [comment]
You should be able use html as you see fit with the transclude option, and if you want to change style to whole text you can use the css element .walkthrough-text

**Comment by noamleib** [comment]
Sorry, long hours... Don't know how I missed it. Thanks man!

**Comment by souly1** [comment]
No problem
