### ISSUE TITLE
The height of header bar in the android platform is being neglected

### ISSUE THREAD

**Issue by grapemix** [souly1/ng-walkthrough#29]
When I am testing on the android platform when using the ionic framework, the height of the header bar is being neglected when I am trying the demo like this:

      <walkthrough
            id="Demo2"
            walkthrough-type="transparency"
            focus-element-id="focus-item"
            icon="arrow"
            main-caption="{{demoCaption2}}"
            icon-padding-left="30"
            icon-padding-top="0"
            force-caption-location="TOP"
            is-active="demoActive2"
            use-button="true">
      </walkthrough>

I have created a pull request for you just in case.

https://github.com/souly1/ng-walkthrough/pull/28

**Comment by souly1** [comment]
This solution in the pull is ok, but I'd rather not add another property. I've checked in a new version (https://github.com/souly1/ng-walkthrough/releases/tag/v0.4.2) which should be more automatic and generic, and also solving the server call for icons. It would be great if you could check it out in your code and update if issue solved.
Thanks

**Comment by grapemix** [comment]
Sorry for the late reply. I tried the version 0.4.2 and everything works fine. Thanks.
