### ISSUE TITLE
Walkthrough hole not at the right position with header bar in Ionic

### ISSUE THREAD

**Issue by ricolo** [souly1/ng-walkthrough#3]
Hi @souly1, thank you for developing this plugin. When I use it with Ionic header layout, the walkthrough hole is not at the right position as shown below, where "click me" button should be highlighted instead:
![screen shot 2015-08-09 at 8 56 01 pm](https://cloud.githubusercontent.com/assets/1523360/9154955/c0870e6e-3ed9-11e5-9d72-667a7622ccc3.png)

It seems that [angular element's offsetTop](https://github.com/souly1/ng-walkthrough/blob/master/ng-walkthrough.js#L206) does not include the top header bar. [Here](http://codepen.io/hmak/pen/XbGpLy) is an example of the issue.

**Comment by area** [comment]
It looks like someone has fixed this in one of the forks of this repository:

https://github.com/CrearAyT/ng-walkthrough/commit/3e070271711564d7516c936e8fbf1512096f3f5c

**Comment by souly1** [comment]
Well finally back and available to attend such issues, sorry for the delay.
Thanks @area for sharing the link, I've incorporated @pardo-bsso 's changes, updated and thanked him. In the plunker the issue seems solved, Update me with additional issues,
thanks

**Comment by pardo-bsso** [comment]
Thanks guys. I thought that I made a PR for this. Sorry about that.

**Comment by kreck** [comment]
Hey @souly1 - awesome module! However i'm also (and still) experiencing the said problem. Could it be due to the use of tabs?

**Comment by souly1** [comment]
Hi @kreck thanks for the feedback,
I'll try to look into it tomorrow, hopefully fixing this and adding unit tests as well.

**Comment by souly1** [comment]
Hry @kreck , issue fixed and test added.
Enjoy

**Comment by kreck** [comment]
thanks a lot! I'll look into it tomorrow!

**Comment by kreck** [comment]
Update: works as promised! Thanks again!
