### ISSUE TITLE
a connection for 'single_tab' is being called

### ISSUE THREAD

**Issue by grapemix** [souly1/ng-walkthrough#30]
I noticed if I have a directive which includes single_tab in the icon field like this:

    <walkthrough
      icon="single_tap"
      is-round=true
      walkthrough-type="transparency"
      focus-element-id="company"
      force-caption-location="TOP"
      is-active="guideStep0"
      >

a connection (https://WEB_SERVER_IP/single_tap) is started from the chrome dev console.

I already loaded ng-walkthrough.tap_icons.js. And everything seems fine except the mysterious connection is being initialed. Any idea how to fix this problem? Thanks.

**Comment by souly1** [comment]
Closed with new version https://github.com/souly1/ng-walkthrough/releases/tag/v0.4.2

**Comment by grapemix** [comment]
Sorry for the late reply. I tried the version 0.4.2 and everything works fine. Thanks.

**Comment by souly1** [comment]
Cool, thanks!
