### ISSUE TITLE
question: can this be used with caching turned on?

### ISSUE THREAD

**Issue by jfbloom22** [souly1/ng-walkthrough#31]
It looks like the only way to selected an element is by ID.  But if I am caching the views in my Ionic app, won't this cause an issue?

**Comment by souly1** [comment]
It shouldn't cause issues, unless perhaps if your using multiple elements with same id

**Comment by jfbloom22** [comment]
I will sometimes end up with multiple elements with the same ID.  I should be able to workaround that by concatenating something unique onto the end of each element ID.

**Comment by souly1** [comment]
If I understood correctly, that should solve it - as long as the selector is unique, there should be no problem

**Comment by jfbloom22** [comment]
cool thx!
