### ISSUE TITLE
Experiencing ng-walkthrough display bugs with Ionic subheader 

### ISSUE THREAD

**Issue by jeansymolanza** [souly1/ng-walkthrough#33]
Hi, I was wondering if you can help.

![capture](https://cloud.githubusercontent.com/assets/12545590/14366692/f27e88b6-fd0b-11e5-8ab9-5a71cb9e0c12.PNG)

I'm using a [subheader](http://ionicframework.com/docs/components/#subheader) on one of my pages and noticed 2 things:

1) **ng-walkthrough** starts rendering below the subheader. I'd like it to start rendering from straight below the header. Currently this means the positioning of the see-through box is a bit off.

2) Can't see **main-caption** (_force-caption-location="BOTTOM"_)... it appears to be at the bottom of the page. In this case, the user would need to scroll down to see it. Is there anything I can do to make sure that it is placed at the bottom of the current page

This is my code so far:

view: http://pastebin.com/GYx5rupt
controller: http://pastebin.com/i5Ka3cd9
services: http://pastebin.com/7fDDKZ9W

**Comment by souly1** [comment]
Hi @jeansymolanza , I think you can move the walkthrough up the DOM tree and things will work fine. 
Is the pastebin above runnable like plunkr? I tried to understand but couldn't find an activate point. If you'll upload a running example I'll take a look and play around with it a bit.

thanks

**Comment by jeansymolanza** [comment]
Hi @souly. Moving up walkthrough up the DOM tree worked perfectly. Thanks a lot for your help!

**Comment by souly1** [comment]
No problem, thanks for sharing! good luck!
