### ISSUE TITLE
Show walkthrough multiple times

### ISSUE THREAD

**Issue by colaru** [souly1/ng-walkthrough#34]
After I press on "Got it" the walkthrough is hidden. This is fine.
But When I make the is-active = true again, the walkthrough is now shown again. 
Any way to make it visible multiple times?
Thank you!

**Comment by souly1** [comment]
Hi Colaru, please try to set a timeout on is-active = true and see if this solves your issue.

Thanks

**Comment by colaru** [comment]
It works.
Thank you!

**Comment by souly1** [comment]
Cool, enjoy 👍

**Comment by RahulJyala** [comment]
hey guys, can you tell me multiple time walkthrough ?

thanks

**Comment by sengoontoh** [comment]
Can you clarify what you mean by timeout on is-active = true?
I've tried to toggle the scope variable that is assigned to is-active from false to true and it did not show the walkthrough the second time onwards. It only works the first time.
Thanks

**Comment by souly1** [comment]
Hi @sengoontoh , For the second time and beyond, when setting is-active=true; wrap it in a timeout:
$timeout(function(){
    is-active=true;
},100);

Update how it goes. Good Luck!

**Comment by DaniNitro** [comment]
My code for second walkthrough is 
$scope.show = function()
		{
			$timeout(function (){
				$scope.isActive = true;
			},500);
		}
in function and is getting called 'on-walkthrough-hide', still its not working
