### ISSUE TITLE
Help wizard

### ISSUE THREAD

**Issue by colaru** [souly1/ng-walkthrough#35]
I want to have a wizard for help: multiple walkthrough screens. 
Is this possible?

**Comment by souly1** [comment]
Hello Colaru, how are you?
I think you are referring to a 'tour' walkthrough (http://www.uxbooth.com/articles/mobile-design-patterns/), this walkthrough is of tip/dialog/embedded/discoverable type. If you are aiming to a multiscreen walkthrough, you can, however, pop first screen and upon close open another and so forth (this is what I and several others do, see closed issues here for demoes on plunkr)
Hope this helps.
