### ISSUE TITLE
Freezing in Ionic App with Menus (iOS and Android)

### ISSUE THREAD

**Issue by mbaiou** [souly1/ng-walkthrough#36]
The walkthrough sometimes freezes in my Ionic app, and prevents the user from tapping out of it. The walkthrough pops up and I've played with it in the chrome inspector tools. The touch is being registered and is modifying the css but it won't hide the walkthrough. My walkthrough is just an image

**Comment by souly1** [comment]
Hi @mbaiou , could you perhaps share plunkr with a demo of the scenario? otherwise it'll be pretty hard to deal with.
Thanks

**Comment by souly1** [comment]
Closing due to lack of responsiveness
