### ISSUE TITLE
Position Calcualtion wrogn with animation

### ISSUE THREAD

**Issue by Brueni92** [souly1/ng-walkthrough#40]
Ok I did found an Issue in my ionic app.
If I set the the is-active variable to true while the switch animation is on-going, it calcuclates the position of the highlight wrong.
I fixed this for me inserting a delay:
setTimeout(function(){
      $scope.showWalkthrough = true
    }, 500);

**Comment by souly1** [comment]
Hi @Brueni92 , thanks for the input, indeed this is the recommended behaviour at current and not solved from within the directive, might be addressed in future.
Thanks
