### ISSUE TITLE
Icon "arrow" not show

### ISSUE THREAD

**Issue by alissonmn** [souly1/ng-walkthrough#42]
Icon "arrow" not show:
Example:
`<walkthrough
            id="Demo2"
            walkthrough-type="transparency"
            focus-element-id="divTarget"
            icon="arrow"
            main-caption="Click here"
            icon-padding-left="30"
            icon-padding-top="0"
            force-caption-location="TOP"
            is-active="true"
            use-button="true">
 </walkthrough>`

**Comment by souly1** [comment]
Hi @alissonmn, this is the code from the demo, the demo works, so let's figure out what's going on:
* Did you add: 'ng-walkthrough.tap_icons.js' file?
* Does the focus on element divTarget work?

**Comment by alissonmn** [comment]
- Did you add: 'ng-walkthrough.tap_icons.js' file? :: YES
- Does the focus on element divTarget work? :: YES

But "arrow" not display

**Comment by souly1** [comment]
OK,
could you perhaps create a plunkr recreating the symptom, as it is currently working for the demo with the latest code and your example from above is pretty much the same, that could be a great place to start, 

Thanks

**Comment by souly1** [comment]
Hi @alissonmn, an issue with the arrow (https://github.com/souly1/ng-walkthrough/issues/43) has been resolved and a new version uploaded. Tell me if your issue has been fixed and if not please add a plunkr or upload a demo.

Thanks
