### ISSUE TITLE
Arrow and text misplaced

### ISSUE THREAD

**Issue by Floppy1009** [souly1/ng-walkthrough#43]
As I tried to include ng-walkthrough to my Ionic project I've got the problem that the arrow and the text is not placed correctly as you can see on the screenshot below.
I even started a new ionic project to ensure there is nothing else interfering. Still same problem. In fact the screenshot comes from that new project.
Is this a known bug or is it just me? :smile: 
If needed I can provide the project as a zip in case I might have included anything incorrectly.

![capture](https://cloud.githubusercontent.com/assets/10551968/16412833/9a903862-3d2e-11e6-9f75-dea7fa7c31e7.PNG)

**Comment by souly1** [comment]
Could be a bug, as opened recently in https://github.com/souly1/ng-walkthrough/issues/42
A zip or plunkr would be great, as the demo works with the arrow with current code.

Thanks

**Comment by Floppy1009** [comment]
Here the Zip of the project:
If you have installed ionic you can simply run 'ionic serve' to try it.
But i guess you know that :)

[ngWalkthroughTest.zip](https://github.com/souly1/ng-walkthrough/files/337034/ngWalkthroughTest.zip)

**Comment by souly1** [comment]
Cool, I'll try to get to it in the upcoming days.
Thanks!

**Comment by souly1** [comment]
Hi @Floppy1009, new version with fix uploaded. Please update as if issue solved,
thanks

**Comment by souly1** [comment]
Yes, it is set to center of highlighted area on purpose, you can use offsets to change.
Thanks, and good luck
