### ISSUE TITLE
Grey background not showing

### ISSUE THREAD

**Issue by onyoo** [souly1/ng-walkthrough#44]
I ran through all the examples in the [Plunker](http://plnkr.co/edit/kHM9zHCxAA3gPYvedmdw?p=preview)  and there are a few common problems: 
    - walkthrough background is not grey
    - walkthrough container is not overlaying the existing DOM elements 

I'm going to keep looking into this, but any help identifying what is going on would be great.

```
Ionic, v1.3.1
AngularJS v1.5.3
"name": "ng-walkthrough","version": "0.4.3"

```
Demo1:
```
<walkthrough
  id="Demo1"
  walkthrough-type="transparency"
  focus-element-id="target"
  icon="single_tap"
  main-caption="Hello!"
  is-active="true">
</walkthrough>
```
<img width="384" alt="screen shot 2016-07-05 at 7 53 01 am" src="https://cloud.githubusercontent.com/assets/14326883/16576209/911b91e4-4285-11e6-8562-aa3c84060c07.png">

The extra space  below "hello" is from this element:

```
<div class="walkthrough-background disable-user-behavior walkthrough-active" 
     ng-class="{'walkthrough-active': isActive}" 
     ng-show="isActive" 
     ng-click="onCloseClicked($event)" 
     on-touch="onCloseTouched($event)" style="">
<div class="walkthrough-container walkthrough-container-transparency" 
     ng-show="walkthroughType=='transparency'">
<div class="walkthrough-inner walkthrough-top" 
     ng-class="{'walkthrough-top': (!forceCaptionLocation || forceCaptionLocation=='TOP'), 'walkthrough-bottom': forceCaptionLocation=='BOTTOM'}" style="">
<div class="walkthrough-transclude" ng-transclude="">
</div>
<div class="walkthrough-non-transclude-template" ng-show="!hasTransclude">
<div class="walkthrough-text-container">
   <pre class="walkthrough-element walkthrough-text ng-binding" ng-bind="mainCaption">Hello!</pre></div>
<img class="walkthrough-element walkthrough-icon" 
     ng-show="icon &amp;&amp; icon!='arrow'" 
     ng-src="url" 
     style="position: absolute;left:104.0390625px;top:134.46875px;margin-top:-11.666666666666666px;margin-left:-17.5px;">
<div class="walkthrough-element walkthrough-arrow ng-hide" ng-show="icon=='arrow'" style=""></div>
<!-- ngIf: useButton --></div></div></div><div class="walkthrough-container walkthrough-container-tip ng-hide" ng-show="walkthroughType=='tip'" style="">
<div class="walkthrough-transclude" ng-transclude=""></div>
<div class="walkthrough-inner walkthrough-top" 
     ng-class="{'walkthrough-top': ((!forceCaptionLocation &amp;&amp; !tipLocation) || forceCaptionLocation=='TOP' || tipLocation =='TOP'), 'walkthrough-bottom': (forceCaptionLocation=='BOTTOM' || tipLocation =='BOTTOM')}" style="">
<img class="walkthrough-element walkthrough-tip-icon-text-box" ng-class="{'walkthrough-tip-icon-image-front': tipIconLocation=='FRONT', 'walkthrough-tip-icon-image-back': tipIconLocation=='BACK'}" ng-show="icon!='arrow'" ng-src="url">
<!-- ngIf: useButton --><pre class="walkthrough-element walkthrough-tip-text-box ng-binding" ng-class="{'walkthrough-tip-text-box-color-black': tipColor=='BLACK', 'walkthrough-tip-text-box-color-white': tipColor=='WHITE'}" ng-bind="mainCaption">Hello!</pre></div></div>
<!-- Always show as this gives us the gray background -->
<div ng-show="walkthroughType=='transparency' || focusElementId || focusElementSelector"
     class="walkthrough-hole" 
     ng-class="{'walkthrough-hole-round': isRound}"
     style="left:22px;top:110.3125px;width:164.078125px;height:48.3125px;"></div>
<div ng-show="hasGlow &amp;&amp; (focusElementId || focusElementSelector)" 
     class="walkthrough-hole walkthrough-hole-glow ng-hide" 
     ng-class="{'walkthrough-hole-round': isRound}" style="left:22px;top:110.3125px;width:164.078125px;height:48.3125px;"></div></div>
```

Demo2:
```
<walkthrough
  id="Demo2"
  walkthrough-type="transparency"
  focus-element-id="target"
  icon="arrow"
  main-caption="Hello!"
  force-caption-location="TOP"
  is-active="true"
  use-button="true">
</walkthrough>
```
<img width="388" alt="screen shot 2016-07-05 at 7 55 12 am" src="https://cloud.githubusercontent.com/assets/14326883/16576277/ef2db0f0-4285-11e6-96be-f90a0897ee47.png">

I realize the arrow should not be drawn twice (that may be from my code). Thanks in advance!

**Comment by onyoo** [comment]
The size of the blank space is proportional to the target item (in this case the OAuth button). So to get out of the walkthrough users must click the blank space or the touch icon.

**Comment by souly1** [comment]
Hi Roberto, nice to e-meet. Several questions:
* On what device don't you see the grey background
* Have you looked into other open/closed issues here?
* Can you perhaps supply a demo with the issues and on what device they appear.

Thanks

**Comment by onyoo** [comment]
Hey Ophir,
- I've tested in browser, iOS emulator, and Android with consistent results.
- I've looked at other issues, but haven't come across a similar one. Will keep looking.
- Working on getting an accurate recreation in Plunker. Will post when done.
Thanks for the speedy response!

**Comment by onyoo** [comment]
Ok. I didn't bring-in ionic, but recreated the results:

https://plnkr.co/edit/BkRQ6wCOmPYkwhcRwmla?p=preview

I'm going to try to work backwards from the demo to see if I can find some more clues.

**Comment by onyoo** [comment]
Caught the mistake in the plunker above. I didn't require the `ng-walkthrough.css` file. This is probably the issue in my app too. A silly mistake as it is in the README. Sorry about that!

**Comment by souly1** [comment]
Cool Onyoo, great the issue was solved, if any other issue surfaces feel free to post.

**Comment by onyoo** [comment]
Ok, so the fix didn't work immediately in the app, but here's why. I was linking to the stylesheet locally with:
`<link src="lib/ng-walkthrough/css/ng-walkthrough.css" rel="stylesheet"></link>`

I verified the path, and the text is identical to the GH link. Yet the code below works correctly. I think there may be something in the way code is loaded? Not sure yet, and will look into this in the future but happy it's working for now...

`<link href="https://rawgit.com/souly1/ng-walkthrough/master/css/ng-walkthrough.css" rel="stylesheet" />`
