### ISSUE TITLE
Show tip after $state.go

### ISSUE THREAD

**Issue by elpofigisto** [souly1/ng-walkthrough#45]
When i have to show next tip on other state,  it shows prev focused area.
After new state is loaded and I go to next step on that state it works well.
On project we're using AngularJs + ui-router. 
How it's possible to wait while state is ready, then focus on needed element ? 

Part of code: 

```
 if(step == 3){
    $scope.focusElementId = null;
    $state.go('some.state', { param : param });

    $timeout(function(){
      $scope.focusElementId = 'some_id';
      $scope.mainCaption = "lorem ipsum lalalalal"
    }, 1000);

  }
```

**Comment by souly1** [comment]
Hi @elpofigisto, nice to meet.

Did you try looking at ui-router's documentation about identifying when transition animation done? maybe their `$stateChangeSuccess` event handler does the job?

Thanks

**Comment by souly1** [comment]
Any update @elpofigisto ?

**Comment by souly1** [comment]
Closing due to lack of responsiveness
