### ISSUE TITLE
Element focus bug

### ISSUE THREAD

**Issue by sunil07t** [souly1/ng-walkthrough#46]
Hi @souly1 I am trying to use ng-walkthrough but there is bug with focus-element-selector attribute. It does not focus on the given DOM element. The id is only set to one element, which is an arrow that changes when the user presses it. 
I am using the following HTML code:

      <walkthrough
            walkthrough-type="transparency"
            focus-element-selector="#dashboard-first-demo"
            main-caption="{{footprintWalk}}"
            is-active="true">
      </walkthrough>

There was a warning when I installed ng-walkthrough that it depends on angular#1.4.3 and the app is currently using angular#1.5.3

**Comment by souly1** [comment]
Hi @sunil07t , sorry for the late reply.
Could you perhaps create a plunkr with a demo of the issue?
Thanks!

**Comment by souly1** [comment]
Any update @sunil07t ?

**Comment by sunil07t** [comment]
Hi @souly1, sorry for late reply. We ended up using another walkthrough.
