### ISSUE TITLE
`Invalid value for <path>` error in console

### ISSUE THREAD

**Issue by umdstu** [souly1/ng-walkthrough#47]
Added the js and css files, injected the module, but when i load the page there are \n's everywhere and a transparent background, and the above error in the console.

`Error: Invalid value for <path> attribute d="M' + startLeft + ',' + startTop + ' Q' + startLeft ...`

In addition to the above error, there's a 'SyntaxError: Unexpected token ILLEGAL' @ Function.jQuery.extend.globalEval.

Any ideas?

**Comment by umdstu** [comment]
So, just noticed that master is at v1, but the version I have, which I pulled from npm, is still at 0.3.1. Can you update npmjs.org version and I can give it another whirl?

Thanks

**Comment by souly1** [comment]
Hi @umdstu , thanks for the update. app version upgraded in npm

**Comment by umdstu** [comment]
Thanks man, i'll give it ago this week!
