### ISSUE TITLE
id property is ignored

### ISSUE THREAD

**Issue by AppwareDev** [souly1/ng-walkthrough#49]
I'm trying to style a specific instance of the walkthrough directive by using an id like this:

`<walkthrough id="walkthrough-step-one"...`

However the id is ignored and seems to be stripped from the HTML once the App runs. This used to work in a previous version. How can I target a specific instance of the walkthrough?

**Comment by souly1** [comment]
Hi @AppwareDev , your absolutely right, a new property was added, `wid` (see readme)  which sets the id of the walkthrough. Take note that the walkthrough element is removed from DOM once closed, so this id will only be relevant when the walkthrough is open.
Update me on how it works out for you.

thanks

**Comment by AppwareDev** [comment]
Aha, thanks.

I still don't seem to be able to use that id in my css though. Should the `wid` act like a traditional HTML id? All I'm trying to do is adjust the CSS styling depending on the active walkthrough.
