### ISSUE TITLE
Handle screen resize

### ISSUE THREAD

**Issue by HugoHeneault** [souly1/ng-walkthrough#5]
Hello, 

Thanks for your plugin. :)

I have an issue when the screen is resized (for example when the keyboard opens on mobile): the hole's position is not updated, nor the icon. 

Any ideas on how to fix it? A resize method, maybe?

Thanks !

**Comment by souly1** [comment]
Hi Hugo, could you perhaps give a specific example and a screenshot? Why would one have the keyboard open during the on boarding? Is it before it activates or is there an input field on the on boarding page itself?

**Comment by HugoHeneault** [comment]
Hi,

Let's assume the user has the keyboard open, and then triggers a walkthrough. 
The walkthrough opens, and in the same time, the keyboard is closing. 

The calculated walkthrough's size won't update after keyboard disappearance... 

I'll try to submit a PR.

**Comment by HugoHeneault** [comment]
See #6 :)

**Comment by souly1** [comment]
Hey Hugo, thanks for the fix, it has been incorporated into the code with several minor changes and an automation test for resizing added.

Thanks
