### ISSUE TITLE
how to Hide walkthrough to start another walkthrough in the same page ?

### ISSUE THREAD

**Issue by RahulJyala** [souly1/ng-walkthrough#53]

**Comment by souly1** [comment]
Hi Rahul, the question is not clear, can you elaborate please?
Thanks

**Comment by RahulJyala** [comment]
i want call another walkthrough  on-walkthrough-hide so i can get multiple walkthrough at the same page to introduce modules ....

here what i'm doing =>


```
<walkthrough id="walkthrough_elem" walkthrough-type="transparency" 
	has-glow="true" is-round="true" main-caption="{{ mainCaption }}" 
	 is-active="isActive" use-button=true icon="single_tap"
	on-walkthrough-hide="nextFunction()">
</walkthrough>`
```

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in focus-element-selector multiple item error in log :

<div ng-controller="WalkthroughController" >
  <walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Rahul</div>



</div>

**Comment by RahulJyala** [comment]
also having problem in  focus-element-selector :


<div ng-controller="WalkthroughController" >
 
<walkthrough id="walkthrough_elem" walkthrough-type="tip" 
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
   focus-element-selector="#focusItem"
	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>


 <div id="focusItem">Anuj </div>


</div>

**Comment by RahulJyala** [comment]
Also Having problem in  ID selector  it is igonered by walkthrough 

I tried both Wid & focus-item-selector for focus in element 


`<div ng-controller="WalkthroughController" >
<walkthrough wid ="step1" walkthrough-type="tip" 
       focusElementId="#step1"
	has-glow="false" is-round="true" main-caption="{{ mainCaption }}" 
  	 is-active="isActive" use-button=true icon="single_tap"
  on-walkthrough-content-clicked="nextFunction()"
	on-walkthrough-hide="nextFunction()">
</walkthrough>

<div id="step1">Anuj </div>
</div>
`

**Comment by RahulJyala** [comment]
also having probleam on focus element , Id  is igonerd by walkthrough however i used bot wid and focus-element-id for focus multiple items

**Comment by souly1** [comment]
In order to switch the text in the walkthrough and reactivate  add into you "nextFunction" method the change and set isActive to true. make sure to wrap it in a $timeout with a reasonable time between them to avoid glitches (500ms+ )

Tell me if this helps.
Thanks

**Comment by RahulJyala** [comment]
this is what i done and worked for me , but having problem in ID it is igonered by walkthrough all nextfunction is changed into single tip , not rendering i want that when my single tip is closed render into anothertip with i selected by ID.

Thanks

**Comment by RahulJyala** [comment]
ID is ignored by walkthrough so it can't render into diff parts all tip shows into one place

 tell me if you have something 
Thank you

**Comment by souly1** [comment]
Hi Rahul wID is used to set the ID of the walkthrough component as it is generated outside the current scope and appended to body

**Comment by RahulJyala** [comment]
ahhh, thanks 
also want to know multiple time walkthrough , how can i conquer that , so far i tried $timeout but still walkthrough shows only once ?

any help 
thanks :)

**Comment by souly1** [comment]
Hi Rahul, assuming I understood you correctly, the same walkthrough but adding changes and then reopening, then yes, this is the process. perhaps try a bigger timeout of 1500ms, see if that makes a change. If that does not work i would debug the code and see that bound values for the walkthrough change as expected, if not, then something is wrong with your binding. if yes, but still does not show, you make sure you using the isActive in the angular lifecycle ($timeout, $http, etc...)

Thanks

**Comment by RahulJyala** [comment]
yes finally it works . 
Thanks man :D

**Comment by souly1** [comment]
Glad to hear, good luck!

**Comment by neerajjain92** [comment]
@RahulJyala How it works, can you tell us I am also facing the same issue.
