### ISSUE TITLE
unable to do next

### ISSUE THREAD

**Issue by mevillep** [souly1/ng-walkthrough#55]
<walkthrough
  is-active="showAccountsWalkthrough"
   id="accounts_view_walkthrough"
   walkthrough-type="transparency"
   focus-element-id="{{ accountsWalkthrough.steps[accountsWalkthrough.currentIndex].id }}"
   main-caption="{{ accountsWalkthrough.steps[accountsWalkthrough.currentIndex].text }}"
   force-caption-location="TOP"
    has-glow = "true"
   on-walkthrough-hide="nextAccountsWalkthrough()"
   is-round="false">
</walkthrough>

            setTimeout(function(){
                 $scope.showAccountsWalkthrough = true;
                 console.log('showAccountsWalkthrough is true');
              }, 3000);
                            $scope.accountsWalkthrough = {
                                steps: [{
                                    id: "w-poGrid",
                                    text: "You will see all your PO's here!"
                                }, {
                                    id: "w-export",
                                    text: "Buttons for exporting to PDF, Excel etc.."
                                }, {
                                    id: "w-query",
                                    text: "Query for Archieved PO's. This will result in massive data result"
                                }],
                                currentIndex: 0
                            };

$scope.nextAccountsWalkthrough = function() {
            
               console.log($scope.accountsWalkthrough.currentIndex);

                  if ($scope.accountsWalkthrough.currentIndex < $scope.accountsWalkthrough.steps.length - 1) {
                      $scope.accountsWalkthrough.currentIndex++;
                         console.log($scope.accountsWalkthrough.currentIndex);

                      console.log($scope.accountsWalkthrough.steps[$scope.accountsWalkthrough.currentIndex]);
                  }
                   $scope.showAccountsWalkthrough = true;
                   console.log( $scope.showAccountsWalkthrough);

            }
When I log, I see my counter and   $scope.accountsWalkthrough.steps updated. But the walkthrough ends and I am unable to see the next.. Also, i can see the id correctly in my javascript. but it is not marked and there is no glow. Please help!

**Comment by mevillep** [comment]
@souly1

**Comment by souly1** [comment]
Hi @mevillep , in order to reload the walkthrough please place the next `showAccountsWalkthrough=true` inside a short timeout.
Tell me if things work out.

Thanks.

P.S If you're using angular/ionic, which you are, it is better you'd use $timeout rather than setTimeout so things will be in the angular lifecycle, otherwise this could be another reason why you would not see changes you expect.

**Comment by mevillep** [comment]
Perfect. Thanks!!

**Comment by stripathix** [comment]
Adding $timeout not working ...only step-1 works
`
  $scope.showMeteogramWalkThrough = true;
          
            $scope.meteogramWalkThrough = {
                steps: [{
                        id: "btn-menuburger",
                        text: "Some text here"
                    },
                    {
                        id: "btn-fav",
                        text: "Some text here"
                    },
                    {
                        id: "btn-help",
                        text: "Some text here"
                    }
                ],
                currentIndex: 0
            };

            $scope.nextMeteogramWalkThrough = function () {
                if ($scope.meteogramWalkThrough.currentIndex < $scope.meteogramWalkThrough.steps.length - 1) {
                    $scope.meteogramWalkThrough.currentIndex++;
                    $timeout(function () {
                        $scope.showMeteogramWalkThrough = true;
                    }, 1000);
                }
            };
`

**Comment by stripathix** [comment]
My bad i was having this in directive markup:
`
is-active="true"
`

Works now :-) awesome...
