### ISSUE TITLE
unable to hide Walkthrough 

### ISSUE THREAD

**Issue by mevillep** [souly1/ng-walkthrough#56]
I have disabled the Got it button. I am having a 'next function ' inside the on-walkthrough-hide. SO when a user clicks anywhere on screen, the on-walkthrough-hide fires the next function and I go to the net step. Now I am wanting to have a button that hides the walkthrough. How am I able to achieve that? If i do a use-button = 'true', it will fie the next function, and go to the next step. Please help. And thanks for this easy and amazing library!
@souly1

**Comment by souly1** [comment]
Hi @mevillep , sorry but i do not understand the issue, could you perhaps clarify.

Thanks
