### ISSUE TITLE
unable to scroll to the element 

### ISSUE THREAD

**Issue by chaosLegacy** [souly1/ng-walkthrough#58]
Hi,
I've start using this awesome directive for my company project and i have some difficulties trying to adapt to my needs so what i'm looking for is a way to let the step increment by user action for example click on add client to continue (see picture 1)
my other problem is i have to adapt that on different devices i've found that the directive does not scroll to the element (see picture 2).
<img width="742" alt="screen shot 2016-12-18 at 9 58 33 am" src="https://cloud.githubusercontent.com/assets/11313734/21292861/991ef8ce-c50a-11e6-98bd-ec53adea92db.png">
<img width="427" alt="screen shot 2016-12-18 at 10 02 06 am" src="https://cloud.githubusercontent.com/assets/11313734/21292865/b99b6eac-c50a-11e6-9bf5-2ce5f87874cc.png">

**Comment by souly1** [comment]
Hi @chaosLegacy ,
about the first issue, this is a v very good idea, but this feature does not exist in the directive...
Regarding your second problem, I'm not sure I understood it, if the item is not on screen, then scroll to element from without the walkthrough and then activate it (if I understood correctly).

Hope this helps,
thanks

**Comment by souly1** [comment]
Closing due to now activity. I'll reopen if you'll still have the issue
