### ISSUE TITLE
How to apply the transclude option?

### ISSUE THREAD

**Issue by jonnysmith1981** [souly1/ng-walkthrough#59]
The documentation suggests it is possible to use HTML within the "walkthrough" block to format the caption:

> Place any HTML code as you like instead of the three dotes as this uses the Angular transclude ability.

But when i try something simple like 
```
<walkthrough
            wid="Demo1"
            walkthrough-type="transparency"
            focus-element-selector="#focus-item"
            icon-padding-left="0"
            icon-padding-top="20"
            is-active="demoActive1">
               <h1>hello</h1>
            </walkthrough>
```

It just renders the _h1_ at the top of the page as if it were normal HTML. This is easily reproduceable on the plunker demo:

![screen shot 2017-01-03 at 16 21 19](https://cloud.githubusercontent.com/assets/8254912/21614274/b5ffd0b2-d1d0-11e6-8f2a-cd7b02896e43.png)

What is the attribute name to enable transclusion?

**Comment by souly1** [comment]
Ho @jonnysmith1981 , form what you show above it seems transclusion is at work (e.g the `hello`).
what exactly do you mean?

**Comment by jonnysmith1981** [comment]
Closing this issue as i completely misunderstood what i should have been doing.
