### ISSUE TITLE
Arrow not displayed

### ISSUE THREAD

**Issue by moosi** [souly1/ng-walkthrough#61]
I am building a mobil (first) application based on angular-material and your plugin perfectly fits my requirements for the onboarding process. Unfortunately I am facing the problem that the arrow I like to use is not getting displayed. If I use any of the icons it will show up at the correct position.

I used the demo to start with:

 ```
<walkthrough
          wid="Demo2"
          walkthrough-type="transparency"
          focus-element-selector="#focus-item"
          icon="arrow"
          main-caption="{{demoCaption2}}"
          icon-padding-left="30"
          icon-padding-top="0"
          force-caption-location="TOP"
          is-active="demoActive2"
          use-button="true">
  </walkthrough>f
```

Angular: 1.3.20, ng-walkthrough: 1.0.4 

Do you have any ideas what could cause this issue? If not I can create a plnkr for you.

**Comment by souly1** [comment]
Hi @moosi , sorry for the late reply.
Did you manage?
I'm not sure as to the issue, if you can create a plunkr I could take a look.
