### ISSUE TITLE
not showing

### ISSUE THREAD

**Issue by ro8in** [souly1/ng-walkthrough#63]
Ok feeling a bit stupid here,

but i included the js en css files

and i add the following html to one of my templates

```
 <walkthrough
              is-round=true
              walkthrough-type="transparency"
              focus-element-selector="#focusItem"
              icon="single_tap"
              main-caption="This is some text"
              is-active="isActive"
              use-button=true>

     test test
      </walkthrough>
```

but nothing is showing.. Also no JS errors or anything..

What am I missing?

**Comment by ro8in** [comment]
I added the following console log to the directive just to make sure its started

console.log('walkthrough directive started');

and it shows in my console when i load the app.

**Comment by ro8in** [comment]
never mind the active true i am stupid

**Comment by souly1** [comment]
Hi @ro8in , thanks for reaching out, glad the issue was solved.
