### ISSUE TITLE
I want to show straight Arro from bottom up

### ISSUE THREAD

**Issue by hanifraj-virtueinfo** [souly1/ng-walkthrough#65]
![004](https://cloud.githubusercontent.com/assets/16152546/23748231/bd017bc2-04e8-11e7-8866-85a317b19d25.png)

Please see attached image i want to show arrow as stright & in this library arrow direction is only right (ex. -> ) but i want arrow direction left (ex. <- ) please i waiting for your response quickly.

Thanks

**Comment by souly1** [comment]
Hi @hanifraj-virtueinfo , I do not currently have capacity to deal with it. You are more than invited, however, to make changes on this open source library as you feel fit.

Thanks
