### ISSUE TITLE
How to change tap icons?

### ISSUE THREAD

**Issue by rajesh-vi** [souly1/ng-walkthrough#66]
Hello,

I'm using ng-walkthrough for displaying tutorial in my app and I want to change tap icons which is defined in **ng-walkthrough.tap_icons.js**.
Can you please guide me to do that?

Thanks

**Comment by souly1** [comment]
Sure,
what you need to do is convert the png image to a base64 array, then just copy paste & replace the current values in the file.
Another option is changing the code a bit to load images from outside as icon, if fits your needs.

Good luck!

**Comment by rajesh-vi** [comment]
Hello @souly1 
I don't think change code in package directly, is there any way to override that base64?

Thanks

**Comment by souly1** [comment]
Sorry Rajesh, nothing for that specifically. You can, however, set any icon you want using the "icon" attribute:
`icon` (optional) - Any walkthrough type. If set to any of the predefined values ("single_tap", "double_tap", "swipe_down", "swipe_left", "swipe_right", "swipe_up"), in such case the icon will be bound to focus element (if exists), make sure to add 'ng-walkthrough.tap_icons.js' following instructions above. any other icon can be used and will be loaded from supplied folder
