### ISSUE TITLE
Fix single_tap 

### ISSUE THREAD

**Issue by hanifraj-virtueinfo** [souly1/ng-walkthrough#67]
![005](https://cloud.githubusercontent.com/assets/16152546/23749782/e215e5a4-04ef-11e7-8833-c6264aa48091.png)

I have fabbutton at bottom right in my application. and **single_tap** icon is showing out of device screen.
See attached image.

Second question : can i decrease icon size in this library ?

Please response me ASAP

**Comment by souly1** [comment]
hello, I do not understand your question:
You can move the icon using attributes `icon-padding-left` and `icon-padding-top`
And you can change image size using CSS on the image.

Hope this helps. good luck!
