### ISSUE TITLE
Rotate Hand icon

### ISSUE THREAD

**Issue by giomarino** [souly1/ng-walkthrough#69]
I have an element in the bottom of the page, if I use the hand icon, it will be hide:
<img width="543" alt="schermata 2017-03-19 alle 09 50 05" src="https://cloud.githubusercontent.com/assets/7312722/24079493/814dcc86-0c89-11e7-8d34-8663ebcf38cf.png">
How I can rotate the icon?

**Comment by souly1** [comment]
Hi @giomarino , thanks for reaching out.
You can try to rotate via css or switch the image with another, there is no current built in support for the feature. Sorry

**Comment by giomarino** [comment]
Okok...No problem, thank you for this awesome library!
