### ISSUE TITLE
Bower tag support

### ISSUE THREAD

**Issue by djett41** [souly1/ng-walkthrough#7]
right now when doing a bower install ng-walkthrough , your master branch is installed rather than a specific release.  In order to tag and release, from your root dir do 

    bower version patch

This will create a tag for you and increment your patch version.  Then push the tag upstream and bower will automatically register that version with your plugin.  So when you do

    bower info ng-walkthrough

You will then see your latest version/release, rather than your bower.json file which is how it is now.  Thanks!  Great plugin!

**Comment by souly1** [comment]
Hi Devin, thanks for the post input and feedback.
I've added a tag (did it give the result you meant?), I'm not sure if I'll continue to maintain tag versioning at this moment as the walkthrough is still in pretty early stages, perhaps in the future.

**Comment by djett41** [comment]
No prob, yep everything good to go thanks!  Cool!  Even though you're in early stages it's still a good idea to version your pull requests to MASTER so your users wont be affected by any changes you make.  For example, If i'm using your plugin, then you commit something that breaks a feature I need, without versioning, people wont be able to use bower to install the version they need.  

Thanks again though buddy!!

**Comment by souly1** [comment]
Cool, will take into consideration, thanks again.
