### ISSUE TITLE
Button caption missing

### ISSUE THREAD

**Issue by stripathix** [souly1/ng-walkthrough#70]
Directive not have any mapping for buttonCaption
`
buttonCaption: '@?',
`

`  if(scope.buttonCaption === undefined ){
                          scope.buttonCaption = BUTTON_CAPTION_DONE;
                        }`

**Comment by souly1** [comment]
Hey @stripathix , can you be more specific,
Checking it here it looks working with 'Got it!' caption

**Comment by stripathix** [comment]
Yeah, it does shows 'Got it!' caption... by default but not able to configure it:

**In documentation it is like this to configure Got it caption**
button-caption (optional) - Customize the text of the dismiss button if present, default is "Got it!".

But looking inside ng-walthrough.js, directive is not accepting buttonCaption attribute...

It always shows 'Got it' caption

**Comment by souly1** [comment]
@stripathix , where are you looking at? 
Looking at code I see:
`scope.buttonCaption = scope.buttonCaption || BUTTON_CAPTION_DONE;`
and setting `button-caption = "Go!"` on the directive set caption to `Go!`

**Comment by stripathix** [comment]
Ohhhhh...
Doing **npm install ng-walkthrough --save** installs 1.0.2  version and in this version buttonCaption was not an option.... sowieee 

Shashwats-MacBook-Pro:exporter shashwat$ npm install ng-walkthrough --save
exporter@1.0.0 /Users/shashwat/projects/expimp/exporter
└── ng-walkthrough@1.0.2

**Comment by souly1** [comment]
No prob.
Thank you, updated NPM
